baseurl = "http://ludovic.coullet.net/"
languageCode = "fr-fr"
title = "La Revanche du Site"
# Enable comments by entering your Disqus shortname
disqusShortname = "lcoullet"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-729622-7"
theme = "nofancy-master"

publishDir = "docs"

[permalinks]
	post = "/:title"

[params]
	name = "Ludovic Coullet"
	description = "Le fils de la revanche"
	topmenu="categories"

[author]
	name = "Ludovic Coullet"
	github = "lcoullet"
	linkedin = "lcoullet"
	gaID = "UA-729622-7"
	twitter = "lcoullet"
