baseurl = "http://ludovic.coullet.net/"
languageCode = "fr-fr"
title = "La Revanche du Site"
# Enable comments by entering your Disqus shortname
disqusShortname = "lcoullet"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-729622-7"
theme = "hikari-theme"

publishDir = "docs"

[permalinks]
	post = "/:title"

[params]
	name = "Ludovic Coullet"
	description = "Le fils de la revanche"
	copyright = "PROPULSÉ PAR [HUGO](//gohugo.io) - THEME: [HIKARI](//github.com/digitalcraftsman/hugo-hikari-theme) - © Ludovic Coullet"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Moins vieux"
	older = "Plus vieux"

	pageNotFoundTitle = "Petit problème de nos amis de la technique, qui nous disent..."
	pageNotFoundSubtitle = "Sorry, but the requested page wasn’t <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Salut c'est Ludo !"
	bio = "Ludovic Coullet"
	subscribe = "Pour les anciens"
	followme = "Suivez-moi"

	# Enable Google search
	search_enabled = false
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "Github"
		url = "//github.com/lcoullet"

	[[params.offcanvas.socialnetworks]]
		name = "Twitter"
		url = "//twitter.com/lcoullet"

	[[params.offcanvas.socialnetworks]]
		name = "Mastodon"
		url = "//dancingbanana.party/@blud"
